version: "3"

services:
  php:
    build:
      context: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
  nginx:
    image: nginx:alpine
    ports:
      - "${API_PORT:-8000}:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
